/** @type {import('tailwindcss').Config} */
export default {
  mode: 'jit',
  safelist: [
    "bg-red-500",
    "bg-pink-500",
    "bg-purple-500",
    "bg-violet-500",
    "bg-indigo-500",
    "bg-blue-500",
    "bg-cyan-500",
    "bg-teal-500",
    "bg-emerald-500",
    "bg-green-500",
    "bg-lime-500",
    "bg-yellow-500",
    "bg-orange-500",

    "text-red-500",
    "text-pink-500",
    "text-purple-500",
    "text-violet-500",
    "text-indigo-500",
    "text-blue-500",
    "text-cyan-500",
    "text-teal-500",
    "text-emerald-500",
    "text-green-500",
    "text-lime-500",
    "text-yellow-500",
    "text-orange-500",

    "border-red-500",
    "border-pink-500",
    "border-purple-500",
    "border-violet-500",
    "border-indigo-500",
    "border-blue-500",
    "border-cyan-500",
    "border-teal-500",
    "border-emerald-500",
    "border-green-500",
    "border-lime-500",
    "border-yellow-500",
    "border-orange-500",

  ],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "gray-secondary": "#F1F3F5",
        "gray-primary": "#868E96",
        "gray-darker": "#343A40",
        "red-secondary": "#FFE3E3",
        "red-primary": "#FA5252",
        "pink-secondary": "#FFDEEB",
        "pink-primary": "#E64980",
        "grape-secondary": "#F3D9FA",
        "grape-primary": "#BE4BDB",
        "violet-secondary": "#E5DBFF",
        "violet-primary": "#7950F2",
        "indigo-secondary": "#DBE4FF",
        "indigo-primary": "#4C6EF5",
        "blue-secondary": "#D0EBFF",
        "blue-primary": "#228BE6",
        "cyan-secondary": "#C5F6FA",
        "cyan-primary": "#15AABF",
        "teal-secondary": "#C3FAE8",
        "teal-primary": "#12B886",
        "brand-secondary": "#C2F7FA",
        "brand-primary": "#208D8E",
        "green-secondary": "#D3F9D8",
        "green-primary": "#40C057",
        "lime-secondary": "#E9FAC8",
        "lime-primary": "#82C91E",
        "yellow-secondary": "#FFF3BF",
        "yellow-primary": "#FAB005",
        "orange-secondary": "#FFE8CC",
        "orange-primary": "#FD7E14",
      },
      fontFamily: {
        IranYekan: ["Iranyekan", "sans-serif"],
      },
      scrollbarGutter: {
        stable: 'stable',
      },
    },
  },
  plugins: [require("daisyui"),
  function ({ addUtilities }) {
    addUtilities({
      '.scrollbar-gutter-stable': {
        'scrollbar-gutter': 'stable',
      },
    });
  },
  ],
  daisyui: {
    themes: ["light", "dark"],
  },
};


